
import java.text.DecimalFormat;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luis.hrevangelista
 */
public class callPage extends javax.swing.JFrame {

    /**
     * Creates new form callPage
     */
    public callPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        genero = new javax.swing.JComboBox<>();
        xv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        R = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setText("Escolha um gênero");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 40, 120, 15);

        genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "homem", "mulher" }));
        genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generoActionPerformed(evt);
            }
        });
        getContentPane().add(genero);
        genero.setBounds(110, 60, 100, 24);

        xv.setText("0");
        xv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xvActionPerformed(evt);
            }
        });
        getContentPane().add(xv);
        xv.setBounds(30, 120, 71, 30);

        jLabel2.setText("peso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 95, 80, 20);

        jToggleButton1.setText("Calcular");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(260, 250, 110, 25);
        getContentPane().add(R);
        R.setBounds(30, 160, 350, 30);

        setSize(new java.awt.Dimension(416, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generoActionPerformed

    private void xvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xvActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        String msg, gr, caloriaReduzida;
        double x, peso; 
        gr = genero.getSelectedItem().toString();
        peso = Double.parseDouble(xv.getText());
         DecimalFormat df = new DecimalFormat("0.00");
       
        if(gr.equals("homem")){
            x = (0.063 * peso + 2.896)*239;
           caloriaReduzida = df.format(x);
            msg = "Você gasta " +  caloriaReduzida + " calorias por dia";
            R.setText(String.valueOf(msg));
        }else if(gr.equals("mulher")){
            x = (0.062 * peso + 2.036) * 239;
           caloriaReduzida = df.format(x);
            msg = "Você gasta " +  caloriaReduzida + " calorias por dia";
            R.setText(String.valueOf(msg));
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(callPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(callPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(callPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(callPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new callPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R;
    private javax.swing.JComboBox<String> genero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField xv;
    // End of variables declaration//GEN-END:variables
}
