
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kaique.acabral
 */
public class Equacao extends javax.swing.JFrame {

    /**
     * Creates new form Equacao
     */
    public Equacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        A = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Delta = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        btnexp = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resolução de Equação de segundo grau");
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("=0");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 20, 50, 50);

        A.setBackground(new java.awt.Color(0, 153, 51));
        A.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        A.setForeground(new java.awt.Color(204, 255, 204));
        A.setText("0");
        getContentPane().add(A);
        A.setBounds(50, 30, 40, 30);

        B.setBackground(new java.awt.Color(0, 153, 51));
        B.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        B.setForeground(new java.awt.Color(204, 255, 204));
        B.setText("0");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        getContentPane().add(B);
        B.setBounds(140, 30, 40, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("x² +");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 20, 50, 50);

        C.setBackground(new java.awt.Color(0, 153, 51));
        C.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        C.setForeground(new java.awt.Color(204, 255, 204));
        C.setText("0");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        getContentPane().add(C);
        C.setBounds(220, 30, 40, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("x +");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 20, 50, 50);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 153));
        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 70, 210, 30);

        Delta.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        Delta.setForeground(new java.awt.Color(0, 102, 0));
        Delta.setText("O valor de Delta é:");
        getContentPane().add(Delta);
        Delta.setBounds(50, 120, 300, 30);

        R2.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        R2.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(R2);
        R2.setBounds(0, 220, 450, 50);

        jLabel7.setText("c");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 10, 34, 16);

        jLabel8.setText("a");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 10, 34, 16);

        jLabel9.setText("b");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(150, 10, 34, 16);

        R1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        R1.setForeground(new java.awt.Color(0, 102, 0));
        getContentPane().add(R1);
        R1.setBounds(10, 170, 450, 50);

        btnexp.setBackground(new java.awt.Color(0, 153, 51));
        btnexp.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnexp.setForeground(new java.awt.Color(153, 255, 153));
        btnexp.setText("explicação");
        btnexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexpActionPerformed(evt);
            }
        });
        getContentPane().add(btnexp);
        btnexp.setBounds(270, 70, 100, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Luis\\Downloads\\menupage.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 410, 320);

        setSize(new java.awt.Dimension(425, 327));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int va, vb, vc, vdelta;
        String delt;
        String result[] = new String[2];
        double vx1, vx2;
        try{
        va  = Integer.parseInt(A.getText());
        vb = Integer.parseInt(B.getText());
        vc = Integer.parseInt(C.getText());
        if(va == 0){
            JOptionPane.showMessageDialog(null, "Isso não é uma equação de segundo grau!");
        }else{
            vdelta = vb * vb - 4 * va  * vc;
             delt = "O valor de delta é: " + vdelta;
            Delta.setText(String.valueOf(delt));
            result = deltb(va, vb, vc, vdelta);
            R1.setText(String.valueOf(result[0]));
             R2.setText(String.valueOf(result[1]));
        }
        }catch (NumberFormatException y) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexpActionPerformed
        new expPage().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnexpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField B;
    private javax.swing.JTextField C;
    private javax.swing.JLabel Delta;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R2;
    private javax.swing.JButton btnexp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

    private String[] deltb(int va, int vb, int vc, int vdelta) {
        String msg[] = new String[2];
        double  vx1, vx2;
        String x1, x2;
        DecimalFormat df = new DecimalFormat("0.00");
        if (vdelta < 0) {
            JOptionPane.showMessageDialog(null, "Não há X real possivel");
        } else if (vdelta == 0) {
            vx1 = -vb + Math.sqrt(vdelta) / 2 * va;
            x1 = df.format(vx1);
            msg[0] = "O valor de x é" + vx1;
            msg[1] = "";
        } else {
            vx1 = -vb + Math.sqrt(vdelta) / 2 * va;
            vx2 = -vb - Math.sqrt(vdelta) / 2 * va;
            x1 = df.format(vx1);
            x2 = df.format(vx2);
            msg[0] = "O valor de x1 é " + x1;
            msg[1] = "o valor de x2 é " + x2;
        }
        return msg;
    }
}
