/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis
 */
public class expPage extends javax.swing.JFrame {

    /**
     * Creates new form expPage
     */
    public expPage() {
        initComponents();
        Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(true);
            callPage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        explica = new javax.swing.JComboBox<>();
        xpPage = new javax.swing.JLabel();
        callPage = new javax.swing.JLabel();
        imcPage = new javax.swing.JLabel();
        matr2x2 = new javax.swing.JLabel();
        Tpage = new javax.swing.JLabel();
        Qpage = new javax.swing.JLabel();
        matr3x3 = new javax.swing.JLabel();
        eq2Page = new javax.swing.JLabel();
        Rpage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        explica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "explicações", "calorias", "IMC", "equação 2 grau", "triângulo", "quadrado", "retângulo", "matriz 2x2", "matriz 3x3" }));
        explica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explicaActionPerformed(evt);
            }
        });
        getContentPane().add(explica);
        explica.setBounds(220, 10, 110, 22);

        xpPage.setForeground(new java.awt.Color(0, 0, 0));
        xpPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/expPage.png"))); // NOI18N
        xpPage.setText("expPage");
        getContentPane().add(xpPage);
        xpPage.setBounds(0, 0, 600, 620);

        callPage.setForeground(new java.awt.Color(0, 0, 0));
        callPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/callexp.png"))); // NOI18N
        callPage.setText("callPage");
        getContentPane().add(callPage);
        callPage.setBounds(0, 0, 600, 590);

        imcPage.setForeground(new java.awt.Color(0, 0, 0));
        imcPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/imcexp.png"))); // NOI18N
        imcPage.setText("imc");
        getContentPane().add(imcPage);
        imcPage.setBounds(0, 0, 600, 590);

        matr2x2.setForeground(new java.awt.Color(0, 0, 0));
        matr2x2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/matr2x2.jpeg"))); // NOI18N
        matr2x2.setText("matr2x2");
        getContentPane().add(matr2x2);
        matr2x2.setBounds(0, 0, 600, 590);

        Tpage.setForeground(new java.awt.Color(0, 0, 0));
        Tpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/tpageexp.png"))); // NOI18N
        Tpage.setText("Tpage");
        getContentPane().add(Tpage);
        Tpage.setBounds(0, 0, 600, 590);

        Qpage.setForeground(new java.awt.Color(0, 0, 0));
        Qpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/qpageexp.jpeg"))); // NOI18N
        Qpage.setText("Qpage");
        getContentPane().add(Qpage);
        Qpage.setBounds(0, 0, 600, 590);

        matr3x3.setForeground(new java.awt.Color(0, 0, 0));
        matr3x3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/mat3x3.png"))); // NOI18N
        matr3x3.setText("matr3x3");
        getContentPane().add(matr3x3);
        matr3x3.setBounds(0, 0, 600, 620);

        eq2Page.setForeground(new java.awt.Color(0, 0, 0));
        eq2Page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/eq2exp.png"))); // NOI18N
        eq2Page.setText("eq2Page");
        getContentPane().add(eq2Page);
        eq2Page.setBounds(0, 0, 600, 590);

        Rpage.setForeground(new java.awt.Color(0, 0, 0));
        Rpage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/Rpage.png"))); // NOI18N
        Rpage.setText("Rpage");
        getContentPane().add(Rpage);
        Rpage.setBounds(0, -20, 600, 620);

        setSize(new java.awt.Dimension(617, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void explicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explicaActionPerformed
        String op;
        op = explica.getSelectedItem().toString();  
        if(op.equals("calorias")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(true);
        }else if(op.equals("IMC")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(true);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("equação 2 grau")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(true);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        } else if(op.equals("matriz 2x2")){
             Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(true);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("matriz 3x3")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(true);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("triângulo")){
            Qpage.setVisible(false);
            Tpage.setVisible(true);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("retângulo")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(true);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("quadrado")){
            Qpage.setVisible(true);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(false);
            callPage.setVisible(false);
        }else if(op.equals("explicações")){
            Qpage.setVisible(false);
            Tpage.setVisible(false);
            imcPage.setVisible(false);
            Rpage.setVisible(false);
            matr2x2.setVisible(false);
            matr3x3.setVisible(false);
            eq2Page.setVisible(false);
            xpPage.setVisible(true);
            callPage.setVisible(false);
        }
    }//GEN-LAST:event_explicaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new expPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Qpage;
    private javax.swing.JLabel Rpage;
    private javax.swing.JLabel Tpage;
    private javax.swing.JLabel callPage;
    private javax.swing.JLabel eq2Page;
    private javax.swing.JComboBox<String> explica;
    private javax.swing.JLabel imcPage;
    private javax.swing.JLabel matr2x2;
    private javax.swing.JLabel matr3x3;
    private javax.swing.JLabel xpPage;
    // End of variables declaration//GEN-END:variables
}
