
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis
 */
public class matrPage extends javax.swing.JFrame {

    /**
     * Creates new form matrPage
     */
    public matrPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        x1v = new javax.swing.JTextField();
        y1v = new javax.swing.JTextField();
        r1v = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        x2v = new javax.swing.JTextField();
        y2v = new javax.swing.JTextField();
        R = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r2v = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        z1v = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        z2v = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        x3v = new javax.swing.JTextField();
        y3v = new javax.swing.JTextField();
        equal = new javax.swing.JLabel();
        r3v = new javax.swing.JTextField();
        plus1 = new javax.swing.JLabel();
        z3v = new javax.swing.JTextField();
        plus2 = new javax.swing.JLabel();
        jbox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        x1v.setText("X");
        getContentPane().add(x1v);
        x1v.setBounds(50, 70, 40, 30);

        y1v.setText("Y");
        getContentPane().add(y1v);
        y1v.setBounds(150, 70, 40, 30);
        getContentPane().add(r1v);
        r1v.setBounds(340, 70, 40, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("+");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 70, 50, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("=");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 70, 50, 30);

        x2v.setText("X");
        getContentPane().add(x2v);
        x2v.setBounds(50, 130, 40, 30);

        y2v.setText("Y");
        getContentPane().add(y2v);
        y2v.setBounds(150, 130, 40, 30);

        R.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(R);
        R.setBounds(0, 260, 260, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("=");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 130, 50, 30);
        getContentPane().add(r2v);
        r2v.setBounds(340, 130, 40, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("+");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 130, 50, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 270, 75, 23);

        z1v.setText("Z");
        getContentPane().add(z1v);
        z1v.setBounds(240, 70, 40, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("+");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 70, 50, 30);

        z2v.setText("Z");
        getContentPane().add(z2v);
        z2v.setBounds(240, 130, 40, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("+");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 130, 50, 30);

        x3v.setText("X");
        getContentPane().add(x3v);
        x3v.setBounds(50, 190, 40, 30);

        y3v.setText("Y");
        getContentPane().add(y3v);
        y3v.setBounds(150, 190, 40, 30);

        equal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        equal.setText("=");
        getContentPane().add(equal);
        equal.setBounds(300, 190, 50, 30);
        getContentPane().add(r3v);
        r3v.setBounds(340, 190, 40, 30);

        plus1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        plus1.setText("+");
        getContentPane().add(plus1);
        plus1.setBounds(110, 190, 50, 30);

        z3v.setText("Z");
        getContentPane().add(z3v);
        z3v.setBounds(240, 190, 40, 30);

        plus2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        plus2.setText("+");
        getContentPane().add(plus2);
        plus2.setBounds(200, 190, 50, 30);

        jbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3x3", "2x2" }));
        jbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jboxActionPerformed(evt);
            }
        });
        getContentPane().add(jbox);
        jbox.setBounds(160, 20, 72, 20);

        setSize(new java.awt.Dimension(416, 329));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int x1, x2, x3, y1, y2, y3, z1, z2, z3, r1, r2, r3;
    String result, op;
    try{
    op = jbox.getSelectedItem().toString();
   if(op.equals("2x2")){
    x1 = Integer.parseInt(x1v.getText());
    x2 = Integer.parseInt(x2v.getText());
    y1 = Integer.parseInt(y1v.getText());
    y2 = Integer.parseInt(y2v.getText());
    r1 = Integer.parseInt(r1v.getText());
    r2 = Integer.parseInt(r2v.getText());
    result = mat2(x1, x2, y1, y2, r1, r2);
    R.setText(String.valueOf(result));
   }else{
    x1 = Integer.parseInt(x1v.getText());
    x2 = Integer.parseInt(x2v.getText());
    x3 = Integer.parseInt(x3v.getText());
    y1 = Integer.parseInt(y1v.getText());
    y2 = Integer.parseInt(y2v.getText());
    y3 = Integer.parseInt(y3v.getText());
    z1 = Integer.parseInt(z1v.getText());
    z2 = Integer.parseInt(z2v.getText());
    z3 = Integer.parseInt(z3v.getText());
    r1 = Integer.parseInt(r1v.getText());
    r2 = Integer.parseInt(r2v.getText());
    r3 = Integer.parseInt(r3v.getText());
    result = mat3(x1, x2, x3, y1, y2, y3, z1, z2, z3, r1, r2, r3);
    R.setText(String.valueOf(result));
    
   }
    }catch (NumberFormatException x) {
            JOptionPane.showMessageDialog(null, "Digite apenas validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jboxActionPerformed
       String op;
       op = jbox.getSelectedItem().toString();
       if(op.equals("3x3")){
          x3v.setVisible(true);
      y3v.setVisible(true);
      r3v.setVisible(true);
      z1v.setVisible(true);
      z2v.setVisible(true);
      z3v.setVisible(true);
      plus1.setVisible(true);
      plus2.setVisible(true);
      equal.setVisible(true); 
       }else{
            x3v.setVisible(false);
      y3v.setVisible(false);
      r3v.setVisible(false);
      z1v.setVisible(false);
      z2v.setVisible(false);
      z3v.setVisible(false);
      plus1.setVisible(false);
      plus2.setVisible(false);
      equal.setVisible(false);
       }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_jboxActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(matrPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(matrPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(matrPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(matrPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new matrPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R;
    private javax.swing.JLabel equal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> jbox;
    private javax.swing.JLabel plus1;
    private javax.swing.JLabel plus2;
    private javax.swing.JTextField r1v;
    private javax.swing.JTextField r2v;
    private javax.swing.JTextField r3v;
    private javax.swing.JTextField x1v;
    private javax.swing.JTextField x2v;
    private javax.swing.JTextField x3v;
    private javax.swing.JTextField y1v;
    private javax.swing.JTextField y2v;
    private javax.swing.JTextField y3v;
    private javax.swing.JTextField z1v;
    private javax.swing.JTextField z2v;
    private javax.swing.JTextField z3v;
    // End of variables declaration//GEN-END:variables

    private String mat2(int x1, int x2, int y1, int y2, int r1, int r2) {
        int D =  (x1 * y2) - (x2 * y1);
    

double  X = ((r1 * y2) - (r2 * y1))/D;

double  Y =  ((x1 * r2) - (x2 * r1))/D;

String msg = "X: " + X + "\n Y: " + Y;

return msg;// Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private String mat3(int x1, int x2, int x3, int y1, int y2, int y3, int z1, int z2, int z3, int r1, int r2, int r3) {
        int D = ((x1 * y2 * z3) + (y1 * z2 * x3 ) + (z1 * x2 * y3)) - ((x3 * y2 * z1) + (y3 * z2 * x1) + (z3 * x2 * y1)) ;
 int Dx = ((r1 * y2 * z3) + (y1 * z2 * r3) + (z1 * r2 * y3)) - ((r3 * y2 * z1) + (y3 * z2 * r1) + (z3 * r2 * y1));
 int Dy = ((x1 * r2 * z3) + (r1 * z2 * x3) + (z1 * x2 * r3)) - ((x3 * r2 * z1) + (r3 * z2 * x1) + (z3 * x2 * r1));
 int Dz = ((x1 * y2 * r3) + (y1 * r2 * x3) + (r1 * x2 * y3)) - ((x3 * y2 * r1) + (y3 * r2 * x1) + (r3 * x2 * y1));
 double X = Dx/D;
 double Y = Dy/D;
 double Z = Dz/D;
 String msg = "X: " + X + "\n Y: " + Y + "\n Z: " + Z;
 return msg;
    }
}
