/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kaique.acabral
 */
public class multPage extends javax.swing.JFrame {

    /**
     * Creates new form multPage
     */
    public multPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mult1 = new javax.swing.JTextField();
        mult2 = new javax.swing.JTextField();
        multresul = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Multiplicação");
        getContentPane().setLayout(null);

        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 290, 90, 23);

        mult1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult1ActionPerformed(evt);
            }
        });
        getContentPane().add(mult1);
        mult1.setBounds(20, 180, 100, 38);

        mult2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult2ActionPerformed(evt);
            }
        });
        getContentPane().add(mult2);
        mult2.setBounds(160, 180, 100, 38);

        multresul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multresulActionPerformed(evt);
            }
        });
        getContentPane().add(multresul);
        multresul.setBounds(330, 180, 100, 38);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("=");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 180, 30, 38);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("x");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 180, 30, 38);

        jLabel4.setText("Digite acima os numeros que deseja Multiplicar");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 290, 250, 16);

        jLabel1.setText("Multiplicação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 70, 80, 16);

        setSize(new java.awt.Dimension(492, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int vmult1, vmult2, vmultresul;
        vmult1 = Integer.parseInt(mult1.getText());
        vmult2 = Integer.parseInt(mult2.getText());

        vmultresul = vmult1 * vmult2;// TODO add your handling code here:

        multresul.setText(String.valueOf(vmultresul));        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mult1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mult1ActionPerformed

    private void mult2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mult2ActionPerformed

    private void multresulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multresulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multresulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(multPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(multPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(multPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(multPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new multPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField mult1;
    private javax.swing.JTextField mult2;
    private javax.swing.JTextField multresul;
    // End of variables declaration//GEN-END:variables
}
