
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luis.hrevangelista
 */
public class powPage extends javax.swing.JFrame {

    /**
     * Creates new form powPage
     */
    public powPage() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        potv = new javax.swing.JTextField();
        numv = new javax.swing.JTextField();
        expoente = new javax.swing.JLabel();
        base = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        R = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        potv.setBackground(new java.awt.Color(51, 51, 255));
        potv.setForeground(new java.awt.Color(0, 0, 0));
        potv.setText("0");
        potv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                potvFocusLost(evt);
            }
        });
        getContentPane().add(potv);
        potv.setBounds(230, 90, 50, 30);

        numv.setBackground(new java.awt.Color(51, 51, 255));
        numv.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        numv.setForeground(new java.awt.Color(0, 0, 0));
        numv.setText("0");
        numv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numvFocusLost(evt);
            }
        });
        getContentPane().add(numv);
        numv.setBounds(100, 90, 50, 30);

        expoente.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        expoente.setForeground(new java.awt.Color(0, 0, 255));
        expoente.setText("0");
        getContentPane().add(expoente);
        expoente.setBounds(120, 120, 120, 80);

        base.setFont(new java.awt.Font("Leelawadee UI", 1, 48)); // NOI18N
        base.setForeground(new java.awt.Color(0, 0, 255));
        base.setText("0");
        getContentPane().add(base);
        base.setBounds(90, 170, 80, 80);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("sobre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 90, 80, 30);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 240, 72, 23);

        R.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        R.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(R);
        R.setBounds(210, 150, 100, 80);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("=");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 190, 34, 40);

        jLabel1.setFont(new java.awt.Font("Leelawadee", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Potência");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 382, 89);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/imagens/page1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 420, 340);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    double num, pot, result;
    try{
    num = Double.parseDouble(numv.getText());
    pot = Double.parseDouble(potv.getText());
    result = Math.pow(num, pot);
    R.setText(String.valueOf(result));
    }catch (NumberFormatException y) {
            JOptionPane.showMessageDialog(null, "Digite apenas valores validos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void numvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numvFocusLost
       int basev;
       basev = Integer.parseInt(numv.getText());
             base.setText(String.valueOf(basev));
       
    }//GEN-LAST:event_numvFocusLost

    private void potvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_potvFocusLost
        int expo; 
        expo = Integer.parseInt(potv.getText());
        expoente.setText(String.valueOf(expo));       // TODO add your handling code here:
    }//GEN-LAST:event_potvFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(powPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(powPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(powPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(powPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new powPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R;
    private javax.swing.JLabel base;
    private javax.swing.JLabel expoente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numv;
    private javax.swing.JTextField potv;
    // End of variables declaration//GEN-END:variables
}
