/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luis.hrevangelista
 */
public class Qpageboa extends javax.swing.JFrame {

    /**
     * Creates new form Qpageboa
     */
    public Qpageboa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        form = new javax.swing.JComboBox<>();
        ladov = new javax.swing.JTextField();
        arestav = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        R = new javax.swing.JLabel();
        labelca = new javax.swing.JLabel();
        labeltl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "área", "perimetro", "volume" }));
        form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });
        getContentPane().add(form);
        form.setBounds(130, 32, 86, 20);

        ladov.setText("0");
        ladov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladovActionPerformed(evt);
            }
        });
        getContentPane().add(ladov);
        ladov.setBounds(140, 80, 60, 30);

        arestav.setText("0");
        arestav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arestavActionPerformed(evt);
            }
        });
        getContentPane().add(arestav);
        arestav.setBounds(140, 130, 60, 30);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 190, 75, 23);

        R.setText("jLabel2");
        getContentPane().add(R);
        R.setBounds(10, 230, 340, 40);

        labelca.setText("comprimento das aresta");
        getContentPane().add(labelca);
        labelca.setBounds(10, 140, 140, 16);

        labeltl.setText("tamanho do lado");
        getContentPane().add(labeltl);
        labeltl.setBounds(20, 90, 100, 16);

        setSize(new java.awt.Dimension(416, 308));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
    String op;
              
       op = form.getSelectedItem().toString();
       if (op.equals("volume")){
            arestav.setVisible(true);
            ladov.setVisible(false);   
            labeltl.setVisible(false);
            labelca.setVisible(true);
       }else{
            labeltl.setVisible(true);
            ladov.setVisible(true);  
            arestav.setVisible(false);  
            labelca.setVisible(false);
            labelca.setVisible(false);
       }            // TODO add your handling code here:
    }//GEN-LAST:event_formActionPerformed

    private void ladovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladovActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladovActionPerformed

    private void arestavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arestavActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arestavActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String op, msg;
       int L, area, a, vol, peri;
       //arestav.setText("0");
       L = Integer.parseInt(ladov.getText());
           op = form.getSelectedItem().toString();
        if(op.equals("área")){
            area = L*L;
            msg = "A área do quadrado é " +  area + "cm²";
            R.setText(String.valueOf(msg));
        }else if(op.equals("perimetro")){
            peri = L*4;
            msg = "O perimetro do quadrado é " + peri + "cm";
            R.setText(String.valueOf(msg));
        } else if(op.equals("volume")){
            a = Integer.parseInt(arestav.getText());
            vol =  (a * a)* a;
            msg = "O volume do cubo é " + vol + "cm³";
             R.setText(String.valueOf(msg));
        }
                                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qpageboa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qpageboa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qpageboa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qpageboa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qpageboa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel R;
    private javax.swing.JTextField arestav;
    private javax.swing.JComboBox<String> form;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelca;
    private javax.swing.JLabel labeltl;
    private javax.swing.JTextField ladov;
    // End of variables declaration//GEN-END:variables
}
