/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Luis
 */
public class Qpage extends javax.swing.JFrame {

    /**
     * Creates new form Qpage
     */
    public Qpage() {
        initComponents();
        arestav.setVisible(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        form = new javax.swing.JComboBox<>();
        arestav = new javax.swing.JTextField();
        ladov = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        R = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(null);

        form.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "área", "perimetro", "volume" }));
        form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });
        getContentPane().add(form);
        form.setBounds(130, 32, 86, 20);

        arestav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arestavActionPerformed(evt);
            }
        });
        getContentPane().add(arestav);
        arestav.setBounds(130, 160, 60, 30);

        ladov.setText("Lado");
        getContentPane().add(ladov);
        ladov.setBounds(130, 110, 60, 30);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 250, 0, 0);

        R.setText("jLabel2");
        getContentPane().add(R);
        R.setBounds(20, 210, 340, 40);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 180, 75, 23);

        setSize(new java.awt.Dimension(435, 334));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void formActionPerformed(java.awt.event.ActionEvent evt) {                                     
    String op;
              
       op = form.getSelectedItem().toString();
       if (op.equals("volume")){
            arestav.setVisible(true);
            ladov.setVisible(false);         
       }else{
            arestav.setVisible(false);           
       }
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       String op, msg;
       int L, area, peri;
       
       L = Integer.parseInt(ladov.getText());
      
        op = form.getSelectedItem().toString();
        if(op.equals("área")){
            area = L*L;
            msg = "A área do quadrado é " +  area + "cm²";
            R.setText(String.valueOf(msg));
        }else if(op.equals("perimetro")){
            peri = L*4;
            msg = "O perimetro do quadrado é " + peri + "cm";
            R.setText(String.valueOf(msg));
        }
    }                                        

    private void arestavActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Qpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Qpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Qpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Qpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Qpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel R;
    private javax.swing.JTextField arestav;
    private javax.swing.JComboBox<String> form;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField ladov;
    // End of variables declaration                   
}
